include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_CONTACT 5019973@mail.ru)
set(CPACK_PACKAGE_VERSION_MAJOR ${DECDECTREE_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${DECTREE_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${DECTREE_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${DECTREE_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${DECTREE_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Decision tree")

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_DEBIAN_PACKAGE_NAME "dectree-dev")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://mikaelkg.github.io/DecisionTree")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
